### PR TITLE
Financial decimal parsing

### PR DESCRIPTION
**Pull request by reixd**
Allow correct financial calculation using the Decimal data type by letting the JSON parser turn float-like values into Decimal.
    This behaviour can be specified during class creation using the kwarg 'json_parse_int' and 'json_parse_float' to parse INTs and FLOATs into Decimal respectivelly.
    
    Example:

        from decimal import Decimal    
        Stock('aapl', 
                json_parse_int=Decimal, 
                json_parse_float=Decimal
            ).get_dividends(range='1y')

### CODE REVIEW

**Comment by addisonlynch** [comment]
Will look into this. I'm not sure if it's standard to have this sort of feature included in the library, from what I can see with others which are similar. Often people handle on their end, or just use Pandas output formatting (which uses np.float64 for floats, which supports the desired calculations)

**Comment by reixd** [comment]
Relying on float numbers for financial calculations is on the long run not a good idea. 
This resource (http://buildingskills.itmaybeahack.com/book/programming-2.6/html/p13_modules/p13_c03_decimal.html) has a good explanation of it.

My PR  proposes a convenient and discrete method to use the Decimal class to work with numbers. Users which do not need this class an accuracy can remain with the defaults.

**Comment by addisonlynch** [comment]
I am aware. Again, it's not common practice for a wrapper such as this to include the Decimal type explicitly (this package is designed with many of the [Pandas Datareader](https://github.com/pydata/pandas-datareader), [Yahoo Finance](https://github.com/lukaszbanasiak/yahoo-finance), and [Google Finance](https://github.com/hongtaocai/googlefinance) paradigms in mind). I'm not very experienced in these kinds of integrations though, so I am looking into it. Doesn't seem like it would be too much of a problem given that normal user behavior is unchanged.

**Comment by addisonlynch** [comment]
Also would like to avoid the additional dependency (six). This was my mistake, as we weren't supposed to be enforcing flake8 in that ``unicode`` instance. It there's a similar workaround without the dependency that would be great. Thanks again for your help.

**Comment by reixd** [comment]
>  It there's a similar workaround without the dependency that would be great.

Well yes, there are workaround, however you need to catch exceptions, which is also not pretty.

A couple of examples are listed here: https://stackoverflow.com/questions/11301138/how-to-check-if-variable-is-string-with-python-2-and-3-compatibility

```
try:
  basestring
except NameError:
  basestring = str

#[...]

isinstance(s, basestring)
```

**Comment by addisonlynch** [comment]
@reixd thanks. I merged this. Realized there isn't a docs entry but I'll take care of it. We can leave the ``six`` dependency for now, since its on the testing side.

**Pull request merged**
