### PR TITLE
Blacken Code

### LINKED ISSUE #188: Blacken code

### PR DESCRIPTION
**Pull request by yehoshuadimarsky**
- [x] closes #188
- [ ] tests added / passed (not applicable)
- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`
- [x] added entry to docs/source/whatsnew/vLATEST.txt

### CODE REVIEW

**Comment by addisonlynch** [comment]
Thanks.

**Comment by yehoshuadimarsky** [comment]
How do I resolve these conflicts?

**Comment by addisonlynch** [comment]
Force pushed from my branch to help resolve conflicts faster. I am going to limit the line length to 79 to maintain PEP8 compliance

**Comment by addisonlynch** [comment]
Thanks @yehoshuadimarsky

**Pull request merged**
